### ISSUE TITLE
Returns price 0, when no price is available. 

### ISSUE THREAD

**Issue by teebu** [dylants/price-finder#116]
https://www.amazon.com/gp/product/B01FM2UV18

```
{ price: 0,
  category: 'Other',
  name: 'Samsung UN75KS9000 75-Inch TV with HW-K650 Soundbar and UBD-K8500 4K Blu-ray Player' }
```

Price of 0 implies free? It should say something to indicate a price was not available?

**Comment by dylants** [comment]
Log output:

```
  price-finder:site-utils found content with selector: #buybox .a-color-price +18ms
  price-finder:site-utils content is an array, attempting to return first entry +0ms
  price-finder:site-utils price string (lowercased): currently unavailable. +3ms
  price-finder:site-utils found inr in price, converting to number... +0ms
  price-finder:site-utils price (post-process): 0 +1ms
```

Seems the logic believes the price is `INR` which then runs this line of code:

```
price = accounting.unformat(priceString);
```

Which converts `currently unavailable.` to `0`.

Looking at the `accounting` library, this seems to be working as it is defined:
https://openexchangerates.github.io/accounting.js/

Hmm... Not really sure what to do here. Would really rather not verify the value with currency code -- that's what we rely on `accounting` to do.

**Comment by teebu** [comment]
maybe you can check if the value is a number?

**Comment by dylants** [comment]
It's been a while, sorry for not responding. My response to your previous comment is that the contents of the `priceString` is not just a number, but in most cases, contains a currency symbol along with fractions of the amount (not sure what they call that in all currencies). So for example, we might get back `$1.99` which isn't a `number` strictly, it's a `string`. When we send this to the `accounting.unformat` function, it returns the value, `1.99`.

Now in this specific example, it happens to contain the INR symbol prefix `r` (which, yes, is a rather weak check, but it's why it's so close to the bottom of the if/else statements). We assume this is a currency and ask `accounting.unformat` to give us the value. It returns `0` since it's unable to parse it correctly.

So I'd rather not take that logic in house, but leave it to `accounting` to handle. And not sure how else to process this without a very specific if statement for "currently unavailable" which doesn't sound like a good idea either.

**Comment by dylants** [comment]
Closing this issue, please let me know if this is still an issue.
