### ISSUE TITLE
adding item image

### ISSUE THREAD

**Issue by rahulbasu710** [dylants/price-finder#118]
Hey,
 Was wondering how to add item image from the website scraped. Want to use your library as it works great with most websites!

Thanks

**Comment by dylants** [comment]
Hey @rahulbasu710, that's interesting. I think it would have to be something similar to the way the price, name, and category are gathered -- code for each specific site. My worry here is that the image still has to be hosted somewhere for you to see it, and if we scrape the URL but don't download the image, we'll still be using the site's hosting to view the image (which they may not like too much).

Were you thinking of hosting the image somewhere else? Or using the site to host the image?

**Comment by dylants** [comment]
Is this request still a priority for you? If not, I will close the issue (though it can be re-opened in the future if needed).

**Comment by rahulbasu710** [comment]
Yes am still using the library

**Comment by dylants** [comment]
I'm going to close this since I think the amount of work required (that I have brought up above) prohibits doing this. I'd also like to keep this module simple, and know that adding another attribute to gather for each site will lead to more maintenance that I do not want to take on at this time.

If you'd like to submit a pull request to add this feature to all sites, please feel free!
