### ISSUE TITLE
Amazon France or other

### ISSUE THREAD

**Issue by Shuunen** [dylants/price-finder#19]
Hi Dylan; it's been a while :)

How should we handle other Amazon websites than .com like in my case .fr  ? Should we add more selectors to detect name ? In my case I test this url : http://www.amazon.fr/gp/product/B00H090J96

and I get : 
```
Price returned : 79.40
Name returned : NaN
```

because title here is at #productTitle

So do we add selectors to a generic Amazon class or should we add this to a Amazon-fr class ?

**Comment by dylants** [comment]
That's a great question!

Actually, I'm surprised you got that far, because I would have assumed the code would not recognize the site URL:
https://github.com/dylants/price-finder/blob/7982a0c7bf37518d56ed0fb2ea8570d05d1d574b/lib/sites/amazon.js#L124

If it does, or we loosen the check to allow any `amazon` URL, the question still remains: what should we do about the sites for other locales?  I'm okay with adding it to the original site, and allow it to handle it (because some sites might not have multiple locales).  But we probably should make it clear in the query as we add more and more selectors.   Perhaps we can key off the `this._uri` to see what query we should run?

What do you think?

**Comment by Shuunen** [comment]
What do you mean by "key off the this._uri" ?

But yes I think adding more selector in the same file is cleaner, because usually there is no link between the locale of a website and the DOM ids, this is just Amazon funny stuff :palm_tree:  :)

**Comment by dylants** [comment]
Sorry I wasn't very clear :smile: I meant that each site takes in a `uri` which it saves when it's initialized.  So for example, here's the amazon site code:
https://github.com/dylants/price-finder/blob/7982a0c7bf37518d56ed0fb2ea8570d05d1d574b/lib/sites/amazon.js#L13

This site uri contains the locale extension (amazon.com vs amazon.fr) which we could then use later in the find functions (`findNameOnPage`) to see which selectors we should use to find the data on the page.  If we pursued this course of action, we could create a helper function `determineLocale` inside the amazon site code which would return the correct locale based on the `uri`.  Either way, this would allow us to track the selectors for each locale independently, so that we don't have conflicts.

Does that make more sense?

**Comment by Shuunen** [comment]
Yes it seems to be a good solution :)

**Comment by Shuunen** [comment]
Who's on it ?

**Comment by dylants** [comment]
Anyone who has time :smile:

A pull request that fixes this issue would be enough.  I'm not sure when I'll have time -- weekends are the best for me but no promises!

**Comment by dylants** [comment]
@Shuunen what do you think about the work done in PR #24 ?

**Comment by dylants** [comment]
With the changes made in that branch, I tested against: http://www.amazon.fr/gp/product/B00H090J96 and saw the following results:

```
price-finder:price-finder returning itemDetails: {"price":79.4,"category":"Other","name":"Leap Motion Système de reconnaissance de mouvements pour PC et Mac"}
```

**Comment by Shuunen** [comment]
result is correct :)

look at my comment on https://github.com/dylants/price-finder/pull/24

**Comment by dylants** [comment]
Work for this issue was completed in PR #24
