### ISSUE TITLE
Unable to run test for infibeam.com

### ISSUE THREAD

**Issue by rajkumarpb** [dylants/price-finder#37]
So I'm trying to add couple of indian e-commerce sites into this package. Wrote infibeam class and when I try to execute unit test, all I am getting is error!

**Failed Specs:**
1) The Infibeam Site a new Infibeam Site with a populated page : should return t
he price when displayed on the page
   Error: Expected -1 to equal 309.
       at Object.<anonymous> C:\Users\Raj\Documents\GitHub\price-finder\test\uni
t\sites\infibeam-test.js:66:36

My test case is : 

    beforeEach(function() {
                price = 309;
                name = "Callmate 5200 mAh Round Candy Power Bank, multicolor";

                $ = cheerio.load('<div id="sdp-price-details" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"><div class="pricing"><div class="row"><div id="base-price" class="col-md-4"><span style="font-family: rupee">R </span><span class="price linethrough">1,499</span></div></div><div class="row"><meta itemprop="price" content="309"><meta itemprop="priceCurrency" content="INR"><meta itemprop="availability" content="in_stock."><div id="price-after-discount"><span style="font-family: rupee">R </span><span class="price">'+price +'</span></div><div id="discounted-percent">80% OFF</div><div id="discounted-price" value="1,190">[<span style="font-family: rupee">R </span><span class="price">1,190</span>Save]</div></div><div class="catalog-offer"></div></div></div>');
                bad$ = cheerio.load("<h1>Nothin here</h1>");
            });
    it("should return the price when displayed on the page", function() {
                var priceFound = Infibeam.findPriceOnPage($);
                console.log(priceFound);
                expect(priceFound).toEqual(price);
            });

Can someone please tell me what I'm missing. BTW I'm new to Node.js space, so sorry if it sounds very simple.

**Comment by dylants** [comment]
Hi @rajkumarpb, thanks for taking the time to try to add these new sites, it's very much appreciated!  I think there's two parts I want to cover in responding to this issue.  The first being the current issue at hand, and the second being how the recent changes made in #36 affect your additions.

**First, the problem at hand: why does your test not pass?**
It's hard to know completely without looking at the code, so if you continue to experience problems you can try committing to a local branch and pasting a link to that code to inspect further.  But what I would recommend you do is to reduce the size of the HTML block in your `cheerio.load` statement to help focus on the problem.  In the tests within the current code base, you'll note that the amount of HTML is just enough to get the selectors to find the price, category, or name but nothing more.  So it's not a "real" HTML scrape of the website, but instead a partial fragment that has a similar structure.

I would also recommend verifying your source code does in fact find the price of the item in the HTML you're scraping.  If that works then it's just a matter of getting that HTML (or again, a small portion of the HTML) into the test.  Sometimes the test highlights an issue with the code that you may have not noticed until now.

**Second, how do these changes affect your code?**
So there were a lot of changes recently made to price-finder in #36.  I would recommend reading the pull request for more details.  Unfortunately, it may have come at a bad time for you and your site implementation (I apologize for that!).  This project has been updated to use ES6 syntax along with a style guide and ESLint to somewhat enforce that syntax.  This means that you may need to update the site code (along with the tests) to align with that change.

I would recommend updating any forks or clones that you have of the price-finder project to see the updates.  Once you have installed the dependencies (or updated your current install), you should be able to see the changes mentioned above and perhaps see any ESLint issues.  Many editors support ESLint (Atom, Sublime Text, WebStorm) which can provide additional help in understanding any potential issues that may exist.

Again, I apologize for the change, and hope this doesn't deter the goal of your work too much.

Hope that helps!

**Comment by dylants** [comment]
Also, I created a Yeoman generator to add sites which might be of help to you:
https://github.com/dylants/generator-price-finder-site

**Comment by rajkumarpb** [comment]
Thanks for the reply. Took the recent version and will try to incorporate the same.

Regarding the issue in hand, guess I can update the files in my fork so you can see if there is anything wrong. Before I add it in price-finder, I did test my code with a simple program using cheerio and it dod worked fine. Let me add them and will let you know. So that I can add a lot more to this plugin!

**Comment by dylants** [comment]
That code looks fine, I would just try to restrict the test to some HTML elements that contain:

```
div #price-after-discount .price
```

As you've written the price selector in your code.  So avoid the long HTML line you pasted above and instead just use a div, with another div that has that ID, with another div that has that class.

And instead of updating your code to get it working with the changes made in price-finder, you might try using the generator to create the site, unit test, and end to end test.  The instructions on how to use it ar on the project page, which is linked above.

**Comment by rajkumarpb** [comment]
Will try the yeoman generator and let you know. Meanwhile I tried with the following HTML but still no luck! 

    <div><div id="price-after-discount"><div class="price">309</div></div></div>

**Comment by dylants** [comment]
The test fails because there's no symbol for the price `309`.  So if you were to change it to be something like this:

```
<div><div id="price-after-discount"><div class="price">$309</div></div></div>
```

It would work (notice the `$` before the amount).  

The code reads in the amount as a string, and then you call:

```
price = siteUtils.processPrice(price);
```

Which will attempt to parse the string into a Number.  But to accurately understand how to process that string, it needs to know what currency it's in (dollar, euro, yen, etc).  Without the symbol, it's unable to process it accurately, and it returns -1.

I'm not sure what the site has for it's value, since you mentioned you were adding a new site, but without the symbol the code can't process it correctly.  What does the site have normally?  How would it display a large amount, over hundreds, does it use commas?  The `processPrice` code calls to the accounting library:

```
price = accounting.unformat(priceString);
```

You can take a look at the library for more information on how it would process it correctly:
https://github.com/openexchangerates/accounting.js

**Comment by rajkumarpb** [comment]
Now the test is working fine. The site is using some style to display the currency and they simply put a span before the price span. Thanks for the help!! 

BTW can you tell me how to use es6? I tried installing it using npm install es6, node-es6 etc, but no luck!

**Comment by dylants** [comment]
Great, glad you got your tests working!  Concerning your question:

> How can I install ES6 for the yeoman generator to work?

ES6 is just an updated version of JavaScript, so from a Node standpoint, if you're using version 4.x or even 5.x you'll get a lot of that functionality.  Here's a chart which should help illustrate what features are in which versions of Node:
https://kangax.github.io/compat-table/es6/

So if you're using version 4+ of Node, you have access to those features already.  It's just a question on if you choose to use them.  We recently updated price-finder to take advantage of some of those features, and in doing so, forced users to update their version of Node.  That's what caused the breaking changes and the release of 3.0.0.

Hope that helps in understanding.

**Comment by rajkumarpb** [comment]
I get it. I have 5.6.0 installed, yet still I am getting errors like xxx should have 5 spaces but got only 4. And whats baffling me is, the error is not even in my changes. It shows error for all files! I forked you repo and just type >npm test and I'm getting this error!! I'm completely lost, but I hope I will dig a lot more and find the solution. If you know why it happens, please help me fix it. I'm using Windows 7 x64 Professional Edition, Node 5.6.0!

**Comment by dylants** [comment]
This is strange because the tests work in Travis CI (our open source continuous integration environment): https://travis-ci.org/dylants/price-finder

It's possible the editor itself is adding these spaces when you open the files, maybe?  I'd be interested in what happens when you simply clone this repository somewhere (perhaps a tmp directory), and run the tests from there.  Do you still see the problem?  Not sure what else to do here though, unless you have a link to your recent fork that you'd like help looking through.

**Comment by rajkumarpb** [comment]
Thanks dylants! It is indeed the editor which caused all this mayhem! Sorry for all the trouble and thank you once again for the help.

**Comment by dylants** [comment]
No problem, glad you were able to get through those problems.  I'm closing this issue, please re-open if this should not be the case.
