### ISSUE TITLE
Add custom headers for Flipkart API

### ISSUE THREAD

**Issue by rajkumarpb** [dylants/price-finder#59]
So @dylants . It looks like I need to add custom headers to validate the Flipkart API. Do you have any suggestion on how to use them? Because for the next 2 APIs that I'm gonna add, it is required to have  this kind of crazy API validations :sob: , so it will be better if you suggest how to proceed with this.

On the lighter note, Indian shopping sites sucks! I mean, why on earth would they block people from scrape their site, when it is going to bring them traffic! Are they that worried about data protection?

**Comment by dylants** [comment]
A custom header per site is a feature request, but it might be even more complicated if that custom header is a API key.  Do you know if there's any way to avoid this?  If you just make a request to the site, what is returned?  Do they have a public API?  Perhaps one is used that you can find when the browser loads the page (try inspecting the network requests)?

Some sites will guard against scraping to avoid others from listing their prices.  Depending on how much these sites want to enforce this, it may just be something that isn't feasible at this time (meaning we can't support the site).

In general asking folks to supply an API key to use this module is a big hurdle.  We have to think how much work the user will have to go through to use the tool.  So what you're learning should be incorporated into the decision.

**Comment by rajkumarpb** [comment]
When I try to get the data, all I get is Forbidden error! I'm trying to find how to scrape the value without giving API key as header. I tried passing the same header which they passed, but I should have missed something. Will try debugging later and crack this.

**Off-topic** : Meanwhile why is ebay not in the list? Is there any reason why you didn't consider it?

**Comment by rajkumarpb** [comment]
@dylants Why do you mean by "In general asking folks to supply an API key to use this module is a big hurdle"?. I mean, if they want to use particular site(like BestBuy in this case), and we have no option to scrape the value, then don't you think going with the option in hand is the only way?

**Comment by dylants** [comment]
Our original Best Buy implementation just scraped the site, but we added the ability to pull the data from an API to get better results (since the API is predictable).  I still contend that it's an extra step for the client of this module but there's a tradeoff to how valuable and reliable the price-finder module is (with an API) to how easy it is to use (without an API key).  In the end, the API key path is used for Best Buy.  Keep in mind the ease of obtaining an API key is an important aspect to this whole process.

The question should be posed for future site implementations.  I do not think it's a clear answer, and each site implementation will have different tradeoffs.  I think it's important to collect this data and make a decision once we understand it.

**Comment by rajkumarpb** [comment]
I'm doing the same for some famous indian sites and if the procedure to pull data differs from API to API, then I guess I'm not keen on adding one in price finder. Not so soon. May be if real need arises in future. So let me collect the data for other major sites also and we'll decide.

**Comment by rajkumarpb** [comment]
So after giving it a lot of thought, I decide it is better not to do such work at this point of time. If, the need arises, then we can think about it.One good thing is, both APIs use same mechanism but doesn't feel like worth doing it.

So let's wait and see if more and more comes into this ugly way of getting data!

**Comment by dylants** [comment]
What's weird about this whole thing is that the solution requires an API key, but the site is still scraped?  Wouldn't we rather use an API key on an API?  Using an API is supported in price-finder, and can lead to more reliable results (since the API should change less often than the UI of a page).

**Comment by rajkumarpb** [comment]
When I say scraping, I meant the results from API. Sorry if that leads you to think this way! 

What I am trying now is, post the API details as parameters in header. Lets see how it ends up!

**Comment by rajkumarpb** [comment]
@dylants Pushed all my changes to flipkart branch. Yes, a few Travis CI tests are failed, but nothing alarming. Can you please check the code and let me know, if we need to have any other changes or improvements.

The reason I removed e2e for flipkart site is, because obviously it needs API key!

**Comment by dylants** [comment]
Its a bit difficult to understand what was added/removed in the branch.  If you'd like to add the flipkart site to price-finder, I think what would be best is to create a pull request and continue the discussion there.  It feels like this issue perhaps is complete (since it started as a question)?

**Comment by rajkumarpb** [comment]
I've added flipkart.js, flipkart-test.js, flipkart-uris-test.js. Three new files. The reason I don't want a PR is, if it works fine, then i'll be adding the snapdeal site and we can merge this is one go.

Or we can add it at later stage?

**Comment by dylants** [comment]
I'd like to keep one pull request for each feature or work item, to keep things simple to manage.  If there are problems with the tests then we can work on it in the pull request.  But it's difficult to judge what's requested to merge without the pull request.

**Comment by rajkumarpb** [comment]
Ok man. As you wish, I'll issue a new PR for Flipkart changes alone and later for Snapdeal.

**Comment by dylants** [comment]
So, I'm sorry if that's a problem, but please keep in mind: there's no way to add code to the master branch without a pull request.  We have to have it.  And its one of the best ways to signify what's going to be added/changed/deleted because of the diff that's created.

I'd also like to close this issue if the question originally posed to create the issue has been addressed?

**Comment by rajkumarpb** [comment]
I know we need to have PR to merge, but I just wanted to fix any major issues before issuing a PR. So there was never a problem raising a PR. I didn't wanna disturb with frequent PRs and me modifying it. Anyways since the question is no more relevant to the current discussion, I'm closing it.
