### ISSUE TITLE
Add support for greenmangaming.com

### ISSUE THREAD

**Issue by rajkumarpb** [dylants/price-finder#62]
I don't know if many have heard about this, but this is pretty decent site with good deals.

**Comment by dylants** [comment]
Sounds great! Just removing the milestone until we get a better idea of what's going in where.

**Comment by rajkumarpb** [comment]
I don't have an issue in removing milestone, but what do you mean by "until we get a better idea of what's going in where"?. Sorry for asking so many questions, but it's just for getting clarity and making me to be on the same page as you.

**Comment by dylants** [comment]
Releases for this project aren't very well defined, I'll admit.  I started using the milestones to try to get a general grouping together.  But at this point we don't have a 3.2.0 release, so the work done here might go into that rather than the 3.2.1.  Also a 3.2.1 implies a bug fix to the 3.2.0 release, which might happen, but this is a feature request which would go into a major or minor release, not a bugfix release.

**Comment by rajkumarpb** [comment]
Gotcha! Since this work is not going to be major for this, I though I can put it as 3.2.1. I work in a big firm so I have little idea on how the version system works. But anyways, since we are the ones to do things out here, I went berserk with version.

We'll better have a clear scope on how we gonna name releases! For adding a site, for any common feature etc!

**Comment by rajkumarpb** [comment]
Hi @dylants . Need some help from ya man!

For greenmangaming.com, the currency has been placed inside Script as JSON. I've seen that you did the regex stuff for newegg, but when I tried the same it didn't worked.

Can you help me with this? Please refer this [https://github.com/cheeriojs/cheerio/issues/824](url) for the code and what I did. Appreciate your help man!
