### ISSUE TITLE
Best-Buy e2e Tests Failed

### ISSUE THREAD

**Issue by rajkumarpb** [dylants/price-finder#73]
I forked the repo, created branch and code looks same but still Best-Buy e2e fails with this error :

**should have the API key defined (1 failure)**

It looks like the key is encrypted from the repo, so is there anyway I can do this at forked repo? Previously it worked because it was local for me, but since it is forked repo and I don't have gem installed in my PC, it will be helpful if you suggest an alternate. 

Except this, other things are working fine in PR #74.

**Comment by dylants** [comment]
Hmm... this is interesting, great find!  I bet it's because of this:
https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests

I've been thinking about API key use in this project in general, and am thinking that the less that's required the better the user experience is (the end user, given equal reliability, would probably rather not have to register for an API key to use the module).  So perhaps best buy can be configured to use the API if the key is available, and if not, scrape the site.  Then the tests can follow the same pattern.

I'll look at trying to get something put together for this, sorry for the problems!

**Comment by rajkumarpb** [comment]
Great! Meanwhile, I prepare another set of lists of sites we need to add!
